### ISSUE TITLE
free cropping in F2 view

### ISSUE THREAD

**Issue by MoorPoor** [brunoherbelin/vimix#115]
Hello!

Some while ago we had a [discussion about cropping in F2 view](https://github.com/brunoherbelin/vimix/issues/5). 
I want to bring it up again as I think it would be very nice to have the option to crop freely in F2.

The center cropping is good in itself, but in order to be able to select an exact uncentered section, it is quite impractical to switch back and forth between F2 and F4 in order to find the right combination of section and placement by moving the canvas around.

I`m still a fan of using the frame grippers for both: Resizing and cropping by toggling using a keyboard shortcut or double-clicking on the corners or similar.

what do you think?

**Comment by brunoherbelin** [comment]
Good to have your input on this !
I started working on  #106 to allow distortion of sources in F2 Geometry view : 
![image](https://github.com/brunoherbelin/vimix/assets/60393189/78d7d69e-9c50-4ae9-bfb1-240d7284c9ce)

So, indeed, this is linked to the cropping and other features of geometrical transformations.

My problem (well, the challenge I impose to myself for vimix) is that I would like to keep things as minimalist as possible, and unified across views. The use of keyboard keys to change the impact of an action is already busy:

- CTRL : is for selection (toggle in/out of selection : used for batch and multiple source control)
- ALT  : activates the  'snapping cursors' (recently added)
- SHIFT : is already used in the F2 view for keeping proportional aspect ratio for scaling / rotation.

This is why for the moment I wouldn't be in favor of using a modifying key for cropping.

And yes, you are right, there is a duplication of cropping mechanisms between F2 and F4 : in essence, cropping could be done only within F4.

What would you say of the following proposal

- CROPPING : central cropping (as is now) would be transferred to F4 view, avoiding to have to switch view to fine tune between crop and shifting of texturing : these are in effect indeed all operations on how the texture is mapped on a surface.
- SCALING or DISTORTING : those geometric operations would be in F2 view, and the icon on the left corner (instead of current crop icon) would be a TOGGLE between square and distortion manipulation corners :

Mode 'normal' square manipulation
![image](https://github.com/brunoherbelin/vimix/assets/60393189/f3529ac4-7c72-45d0-ae7e-3c08fbc63eb1)

Mode 'distort' corner manipulation
![image](https://github.com/brunoherbelin/vimix/assets/60393189/f9459dbe-ae19-437b-9e6a-bdc86331063d)


Would that work?

**Comment by MoorPoor** [comment]
wow!
cool, that you started with distortion!
to switch between normal and distort corners is something I like a lot, actually so much that I would like to have the same switch for cropping, e.g. in the bottom right corner. Sorry for insisting on this, I think it's so nice to have all forms of manipulation in one view (apart from the special cases in F4) it's just much more intuitive, I guess as soon as you see grippers on the corners, you want to use them and expect cropping in addition to resizing. 

A simple click or double click in the source itself could also switch the corner tools sets. such as in Inkscape.

but wait a minute, what's the difference between "normal" square manipulation and the resizing tool in the lower right corner?

Another thing, if alt key is used to work aligned to the grid, wouldn't it be consistent to also have the rotation aligned to some angles in combination with alt?

**Comment by MoorPoor** [comment]
sounds good!
`yes it is: are you using the latest beta ?`
nope, sorry, I will have a look!

**Comment by brunoherbelin** [comment]
Please try latest Beta 5465a45dc6476ace9633680017781054c29f0943 : 

![20231217232906145_vmixcapture](https://github.com/brunoherbelin/vimix/assets/60393189/17184488-fb84-49d6-9493-16f0e26d02f3)

Toggle geometry edit more to crop: It has corner distortion, side cropping and corner rounding. 
Implementation is not finished and has bugs, but it's usable enough to try and send feedback.

**Comment by MoorPoor** [comment]
ui!
Is there a way for lazy people to quickly install the beta version via snap or flatpak?

**Comment by brunoherbelin** [comment]
Check here; https://github.com/brunoherbelin/vimix/blob/master/flatpak%2FREADME.md

this shows how to create a pre-release flatpak Package

**Comment by MoorPoor** [comment]
thanks,
I like the integration! the switching between the modes seems intuitive enough for me.
Pulling the corners out of the frame isn't possible, but I don't think that's a problem in practice
corner rounding is fun too.

**Comment by brunoherbelin** [comment]
Good that you could test !

>  I like the integration! the switching between the modes seems intuitive enough for me.

I might add a menu item to make it explicit. 
I hesitate to toggle mode on double-clic, as double clic is already used to show the left panel (in every view); changing the meaning of this action would be a little inconsistent with the rest of user experience. Or am I too picky?

> Pulling the corners out of the frame isn't possible, but I don't think that's a problem in practice

In effect, putting a corner outside of the frame requires to scale the source to enlarge it, so that the frame is still encapsulating the whole source. This is not impossible to do, but a bit tricky geometrically (i.e. moving nodes inside while changing the global scale at the same time). 

>  corner rounding is fun too.

There is much more possibilities behind my implementation, and i will follow up later...

**Comment by MoorPoor** [comment]
>  I might add a menu item to make it explicit.

do that in addition for savety , but in general I don't like menu as long as everything is accessible at a glance. That's why I like it the way you've integrated it now! its good.

> This is not impossible to do, but a bit tricky geometrically

then you better leave it as it is. I think this is clear and no further work is needed.

> There is much more possibilities behind my implementation, and i will follow up later...

:D

**Comment by brunoherbelin** [comment]
![image](https://github.com/brunoherbelin/vimix/assets/60393189/c78e6ebb-f45b-4017-9bdb-2d5c2358dea6)

Implementation is done (Beta >= abdc70121d857f57f98d98d026adb9be4a69dcfd )
