### ISSUE TITLE
capture rolldown growing

### ISSUE THREAD

**Issue by kubriel** [brunoherbelin/vimix#118]
hard to describe, but im getting this weird glitch on my debian bullseye so i recorded an video for you:
https://youtu.be/u61FZV8doow
it was there month ago in beta and master, no time to report.

**Comment by kubriel** [comment]
and its happening also in Texturing[F4], see:
https://kubriel.servus.at/uploads/vimix_rolldown_bug.png

**Comment by brunoherbelin** [comment]
> hard to describe, but im getting this weird glitch on my debian bullseye so i recorded an video for you: https://youtu.be/u61FZV8doow it was there month ago in beta and master, no time to report.

Thanks for pointing this out. Should be fixed in Beta 7606baa20b1b8608c0d91494906bfab9e254af9c

If you can't [compile the Beta branch](https://github.com/brunoherbelin/vimix/tree/master/flatpak#build-local-beta-flatpack-package-of-vimix), you can avoid this bug by increasing the scaling of the UI in Settings.

> and its happening also in Texturing[F4], see: https://kubriel.servus.at/uploads/vimix_rolldown_bug.png

humm... here I can't replicate; do you mean the submenu size is increasing?

**Comment by kubriel** [comment]
i just compiled beta, and can confirm that Display's capture got fixed in all scalings, but Player's and Texures not.
again, better to see:
https://youtu.be/NwJvGyhjqK8
might be also that my debian installation is a bit older.

**Comment by brunoherbelin** [comment]
Aha ! It was indeed the same problem in the Capture menu of the Player window! Thanks !
Both menus should be fixed in Beta 698665c4cc1eb5c4605c3d7d27c87c1adee6d539 .

I saw the Texture view context menu moving by itself in your video : really weird indeed... Could not replicate here, so hard to know what is causing it... I will investigate.

**Comment by kubriel** [comment]
can confirm, booth capture menus stands still in all scalings, but i have new behavior with texture context menu in all scalings(not all in the video), look https://youtu.be/s8sLZwUHkYE

**Comment by brunoherbelin** [comment]
I made some changes blindly that could possibly fix the bug (although couldn't verify).
Would you please be able to check on latest releases (0.8.2b) or Beta ? Thanks

**Comment by kubriel** [comment]
heh its still there, but this time its walking left. nevermind, dont waste your resources when you cant reproduce it. i can live with it, and i will test it on some other machine later.

**Comment by MoorPoor** [comment]
weird scrolling is gone in my case, cant see it anymore anywhere.
ubuntu 23.10 snap 8.2

**Comment by kubriel** [comment]
oh, i started to be afraid that its some exotic irregularity of my system.
did you checked the context menu of texture, like in the 7th second of this video?
https://www.youtube.com/watch?v=NwJvGyhjqK8

**Comment by MoorPoor** [comment]
> did you checked the context menu of texture, like in the 7th second of this video?
no scrolling anymore. However, I can't say. whether I ever had a scroll at this exact location. I just remember your initial glitch from first post.

**Comment by kubriel** [comment]
hallo, i updated my installation to debian bookworm, and theese issues dissapeared with master.
