### ISSUE TITLE
Vimix frozen after 2/3 session load

### ISSUE THREAD

**Issue by lupin3rd** [brunoherbelin/vimix#122]
I attach a video registration of the problem... seem that vimix crash after load some sessions...
and the same session that at first load don't have any error... if reloaded don't find video file...
https://www.youtube.com/watch?v=JeOSjkiRBeo

**Comment by brunoherbelin** [comment]
aha! Thanks for the bug report : I did several memory stress test when originally developing the video sources but many changes since then might have caused leaks or missing freeing memory. Also i see the situation is linked to many media pre-loaded but not playing (in standby) : this might be linked to the problem (i.e. source deleted before having played)... For sure a bug that I will fix !

Thanks again for your help in spotting this issue!

**Comment by brunoherbelin** [comment]
Hey ! Please try with Beta 5a077d2f52e65a29cc350e853be1aa662d3c1851

I could replicate similar issues and should have fixed it. Hopefully it was the problem you encountered... Let me know.

**Comment by lupin3rd** [comment]
I confirm that last commit solve the bug!
