### ISSUE TITLE
"Restart on deactivation" bug

### ISSUE THREAD

**Issue by lupin3rd** [brunoherbelin/vimix#133]
With player mode "Stop at end" the "Restart on deactivation" feature don't works. Video not restart when i reactivate the source (if it has reached the end).

**Comment by brunoherbelin** [comment]
Thanks Lupin :+1: 
Although I woudn't call it a bug, rather an "undocumented feature", I understand your request and changed the behavior accordingly in Beta 16fb654b980ce93ecd9600c693f3accb35e232ba

So, instead of the previous ('normal') behavior that a source not playing should not be playing if re-activated, in this case and understandably, re-activating a source with the option now called "rewind on REactivation" now changes the playing status and triggers the source to play.

**Comment by lupin3rd** [comment]
Thank you! I confirm that new beta reactive the source. 👍

**Comment by brunoherbelin** [comment]
> Thank you! I confirm that new beta reactive the source. 👍

Thanks for always being proactive and reactive !  A pleasure collaborating with you :smile:
