### ISSUE TITLE
Dynamically set shader filter variables

### ISSUE THREAD

**Issue by michaelpanik** [brunoherbelin/vimix#139]
I'm using Vimix + Chataigne for real-time video performance. Having the shaders are incredible. The only thing that would push it over the edge would be the ability to control variables in the filter in real-time. Is there some way to do this, possibly through OSC?

**Comment by brunoherbelin** [comment]
Thanks for positive feedback!

Yes, what you ask is supported by vimix in latest version 0.8.2d (currently being submitted as snap and flatpak releases, otherwise accessible from source)

Example; send `/vimix/#0/uniform sf pix 0.9` to set the value of the uniform variable 'pix' to 0.9, assuming source #0 is a clone source and the shader code defined a uniform variable called 'pix'.

More info on the [wiki OSC doc](https://github.com/brunoherbelin/vimix/wiki/Open-Sound-Control-API#attributes-to-control-different-types-of-sources )

**Comment by michaelpanik** [comment]
Incredible! Thank you so much: this is about to take my game to the next level. I'm running a very cool show on Thursday - if video of me running Vimix in a live context would be helpful to you, I'd happily shoot some and send it your way for promotion.

**Comment by brunoherbelin** [comment]
That would be awesome !

We could link / insert it to the vimeo page (https://vimeo.com/vimix), or I was also thinking of a 'Made with vimix' section in the wiki. Let's see.

**Comment by lupin3rd** [comment]
In 0.2 version of my module there are cloneuniform messages:
https://github.com/lupin3rd/vimix-chataigne-module

**Comment by michaelpanik** [comment]
> In 0.2 version of my module there are cloneuniform messages:
> 
> https://github.com/lupin3rd/vimix-chataigne-module
> 
> 

I've got the plugin going - it rules! I'm using a uniform float and the uniform clone mapping but it's not affecting it. Any ideas?

 ![image](https://github.com/brunoherbelin/vimix/assets/25326995/49e53bee-4f54-4900-8156-a59855d1b384)

**Comment by brunoherbelin** [comment]
Two things to check

-  declare uniform without initialization value (this prevents the reset to 0.25 each time GLSL is loaded)
-  In the last version of vimix, when a uniform is registered (after build), there is a slider in the left panel properties of the clone (if you don't have the slider for EFFECT_1, then upgrade)
- there should be a log of the events in vimix: not sure how verbose it is in Release (otherwise compile with Debug)

**Comment by lupin3rd** [comment]
@brunoherbelin how about releasing Vimix version 0.9 ?
There are actually many new features in the development version.
