### ISSUE TITLE
Request: OSC command for "Corner" move in Geometry View

### ISSUE THREAD

**Issue by ThomZenTury** [brunoherbelin/vimix#156]
Hi again!

As written in the first post here is the second of three questions.
Another feature that I could not find to control via OSC commands: moving the 4 corners of a clip in geometry view to "deform" it.

I think it would be really handy to be able to fiddle around with the corners from outside of the Vimix GUI so we could get rid of the mouse fiddling when setting up a scene and switch to a handheld device or similar. Just in case, of course, this seems useful to you and/or others.

One more to come...

**Comment by brunoherbelin** [comment]
Working on this, there is a preliminary implementation in Beta commit ff39f8c458df4f9733ca6641829442a4fbdb38c8.

It takes  8 `f` values, which are 4 pairs or coordinates  (x,y) for all corners: corner 0 (lower left), 1 (upper left), 2 (lower right) and 3 (upper right). Set to zeros to reset all: 

      /vimix/current/corner ffffffff 0 0 0 0 0 0 0 0

The values of the coordinates are between -1 and +1, always centered on the default position (0,0) and in a coordinate system where -1 is left and +1 is right. Thus, lower left corner values can be set to (+1.0, +1.0), and upper right can be set to (-1, -1) as shown here:

![corner coordinates figure](https://github.com/user-attachments/assets/02b86afb-39ff-422a-88c5-0474a21d56e5)

Example: 

      /vimix/current/corner ffffffff 0.5 0.5 0 0 0 0 -0.5 -0.5

Also, animation with timing also works; add a `f` to set a duration in millisecond;

     /vimix/current/corner fffffffff 0.5 0.5 0 0 0 0 -0.5 -0.5 20000


It is not very intuitive, I admit, because it corresponds to the internal implementation. Would that still be usable? We could discuss on how to make it more user friendly...

**Comment by ThomZenTury** [comment]
So awesome!
I already implemented it in the template (which is finally available - but careful - buggy here and there).
I know what you mean with "user friendly". Maybe the array is a bit long, so customizing is not too intuitive. Fortunately O-S-C has the pretty perfect multiXYpad, that is just sending out the same array length.
A bit short on time at the moment but the first things that comes to mind would be:

1. rather 4 arrays with only XY coordinates? (But as I said, perfect for O-S-C with one long array)
2. I had to do a bit of remapping to get the coordinates right for each point - maybe a system from -1 to 1 over the whole picture would be easier (leftBottom = [-1, -1], leftTop = [-1, 1], rightBottom = [1, -1], rightTop = [1, 1] )

I will think a bit more about this...

Aaaand hopefully for your liking - the template and some clips:
https://github.com/ThomZenTury/OSC-Vimix-UI
part1: https://youtu.be/c5HhdBt-ceY
part2: https://youtu.be/fKlg2WOcLbc
more to come...

Have a nice evening!

**Comment by brunoherbelin** [comment]
![Screenshot From 2024-11-25 20-01-44](https://github.com/user-attachments/assets/5523ab66-e154-403d-a683-9efbae2af7d4)

Youhou! playing already with this new OSC interface :smile: !
Thanks! Very excited to explore ! May features already !

FYI, you can also run vimix 'headless' (i.e. witnout UI) and use only this OSC interface (https://github.com/brunoherbelin/vimix/wiki/Command-line-usage).

**Comment by ThomZenTury** [comment]
Oh, my!
Neither haven't I even thought about headless nor did I notice it on the wiki page. This let's me smile over my late dinner. Thank you so much for the hint!

I will for sure look into this and include it in one of the next videos.

Also, very cool to see you testing it!

**Comment by brunoherbelin** [comment]
Excellent! Closing this issue then!
