### ISSUE TITLE
multiple monitor

### ISSUE THREAD

**Issue by DavidLep0le** [brunoherbelin/vimix#21]
Hello
First thanks a lot for this new vimix !

I got a question about monitors/screens.
There is a little of my request in #16 issues.
But i think a output monitor menu is needed.
I think the enhancement to set up multiple monitors, sizes, geometry, decoration and maybe edges or little effects, mapping to compose big pictures would be a great thing.
So let's talk about that...

**Comment by brunoherbelin** [comment]
Thanks for your support and input!

There are two aspects which require different amount of work

1. Menu in the Output window to control the options of the output view
2. Custom geometry and video mapping 

For 1., I agree and its just a matter of finding time for programming it. If you could please suggest what functionality you think would be useful, I could probably implement this very soon.

For 2., this is something I have in mind for a long time, but requires more programming efforts. The Geometry View could allow to organize multiple output frames (pink) and to perform some geometric operations (e.g. to correct for the projection distortion), as well as support different sizes for output (e.g. for devices allowing to plug two monitors on one plug). But this has deeper consequences on the programming foundations and implications on other elements (eg. recorder, output preview window). I am hopeful that someone could help for programming this part.

**Comment by brunoherbelin** [comment]
This should be satisfied in [version 0.8.0.](https://github.com/brunoherbelin/vimix/releases/tag/0.8.0)

Please test  and add comments to improve the Displays view.

**Comment by lanitrock** [comment]
Thank you for creating this wonderful OSS! it's been a total dream come true and one of the easiest software i've ever tried to learn!

A few questions- 
Is it possible with 0.8.0 release to output different video to multiple screens? Not to just mirror the same video to multiple screens but to create a multi channel installation to multiple projector screens? I have the correct HDMI splitter to do so on the hardware side, but have not been able to accomplish software-side in vimix. Is there documentation illustrating multiple output setup?

Also. especially since the last few updates, I have also been experiencing save errors and file location errors- also some issues with .mix files made in older versions of Vimix. is there a batch location error resolution function? I made the mistake of renaming the folder where my files were stored and it threw up a bunch of errors- i tried closing the file and reverting to the old name but the errors did not resolve. I did try the one by one file locate tool to correct the file path, which worked about half the time. Almost always after there were file location errors, the .mix file failed to save properly.

Thanks so much for your help!

**Comment by brunoherbelin** [comment]
Thanks for the enthusiastic comment !

To answer to your first question, the current way to distribute the output of vimix on multiple windows is to use custom fit in each window and select which area of the output to show. An example is given in discussion thread https://github.com/brunoherbelin/vimix/discussions/125 
For sure, we should do a documentation for this, or maybe a video. And yes, thinking of adding output target areas in mixing view is something to be developed.

It is not easy to answer your second question. There might be multiple errors in what you describe. First, if the original file is moved, the .mix session can't know its new location. The way to fix a session is to do 'Replace' on the source that is invalidated, in red in the left panel:
![image](https://github.com/brunoherbelin/vimix/assets/60393189/f072118a-21e4-4199-9ac0-cbea23fbe262)

Otherwise, errors of compatibility between vimix versions are also not easy to solve: backward compatibility can be anticipated, but a .mix file saved with a newer version of vimix might indeed be not compatible with an older version... Or is it something different? 

Do not hesitate to submit a new issue for a each error you encounter; it can be simpler to follow up!
