### ISSUE TITLE
crop tool

### ISSUE THREAD

**Issue by MoorPoor** [brunoherbelin/vimix#5]
Hei!
Is cropping something you are planing to add? Would be great.
Thanks & Greetings!

**Comment by brunoherbelin** [comment]
Yes of course !

A dedicated "Source View" (F4) is planned :
* Global geometric deformation (crop, shear)
* Grid surface distortion 
* Preview with/without shading (filters)

Other ideas?

**Comment by MoorPoor** [comment]
Sounds good!
a source view is for sure useful, but having those crop, shear, distortion options in F2 view by hand would be great too, As scaling and turning is already possible there.
I got it right: shearing/distorion will give us perspective correction, right?

**Comment by MoorPoor** [comment]
Thanks Bruno for the big update.
Here are just a few thoughts on the new F4 window
For me, it is impractical to open a separate window for cropping. It disrupts the collage process a lot. It would be very practical to also have this function in the F2 window, possibly a combination with a shortcut and the corner grippers, as often used in other programs.
The cropped objects in the F2 window keep their outer frame, which is a bit inconvenient if many are behind and on top of each other.
Another point is that the masks do not adapt to the cropped image section but are also cropped.
Thanks!

**Comment by brunoherbelin** [comment]
Thanks for the feedback !

1) Merge Geometry (F2) and Appearance (F4) controls
I understand, but the difficulty is to keep a clear user interface: combining the rectangle for source manipulation (white frame in F2, with 10 corner grips) and the texture manipulation (yellow frame in F4, with 10 corner grips + 2 crop grips) in the same view makes it complicated... One option is to limit the features to make the UI simpler, but I would like to keep maximum flexibility (all features). I'm open to experiment with other ways to visually integrate the texture manipulation within F2 (without changing view)
>> I welcome sketches or photo-montage illustrating how you'd imagine it!

2) Crop outer frame
This was a delicate design choice; originally indeed, the idea was that crop would change the geometry shape too. But this has other consequences: in the Mixing (F1) and Layer (F3) views, what would be displayed? If we apply there the new shape, the frame becomes very large, or very thin, and one cannot recognize which source it is. I tried both and it looked like keeping the original frame shape seemed the simplest to keep it coherent in F1 and F3. 
>> Let me know if, from user's point of view, having a different visual representation of a source in F1-F3 (icon with crop in original frame) and F2 (reduced size after crop) would make sense: I was just afraid that this would be confusing. 

3) Crop mask
Yes indeed. I hesitated, but if from user's perspective it is more logical to scale the mask (instead of crop the mask) I'll change this.

**Comment by MoorPoor** [comment]
1. I Will get back to that later

2. I understand ... would it be a possibility for a good overview in F1 & F3 to keep the original frame view of the file and only to display the cropped frame version in F2?
From my inexperienced view, it would be justifiable as well to show the cropped, smaller version in the real display ratio in F1 and F3.

3. I would understand smaller parts of a material as a new source and think it makes the most sense to let the masks also behave like that. One option that would be worth considering is the order in which masks are used. They are applied to the raw material before trimming, or they are applied to the cropped section if they are set after trimming?!

**Comment by brunoherbelin** [comment]
Just an idea for 3. What if user could also adjust the mask position / scale / orientation? (eg. a blue frame to manipulate)? But then this becomes yet more complicated.

Or then, if we think of it otherwise; do you mean that CROP would be for the collage in F2, but we keep the F4 for texturing manipulation ? This would make sense, no?

**Comment by MoorPoor** [comment]
yes, first point sound complicated,
keeping F4 for texturing sounds useful

**Comment by MoorPoor** [comment]
getting back to point 1 - what about the following option:
![Bildschirmfoto von 2020-12-07 11-13-52](https://user-images.githubusercontent.com/60827766/101338590-75010280-387d-11eb-9cb8-7e3715620a43.png)
outer gripper (green) will scale the image as it is status quo.
inner gripper part (red) will crop the image
alternatively cropping is activated by pressing shortkey (e.g. CTRL) while gripping the scale grippers to keep the interface clean.
![Bildschirmfoto von 2020-12-07 11-13-42](https://user-images.githubusercontent.com/60827766/101338930-f789c200-387d-11eb-9700-c0467b8365e6.png)
another feature that I would highly appreciate would be the option to add multiple additional gripper-points to be able to create a free-form mask.
what do you think?

**Comment by brunoherbelin** [comment]
Thanks for your input ! Really appreciated. I like very much that the design can also be a collaborative work.

For crop in geometry view (F2) here is what I implemented over the weekend:

![Screenshot-20201207192647-1370x836](https://user-images.githubusercontent.com/60393189/101389972-730d6280-38c2-11eb-8de5-b6407855e0cc.png)
![20201207192706681_vmixcapture](https://user-images.githubusercontent.com/60393189/101389982-756fbc80-38c2-11eb-81dc-2203bea8ee34.png)

>> The additinal CROP grip (lower left corner) makes it clear, and you'll see in the next version, the feeling is right when cropping while organizing the collage.

For the masks, yes I totally agree: the F4 view (maybe better called "Texturing" ?) should be the place! I like very much your suggestions and the examples above:
- free form : that's ultimately the best solution, but I need a bit of time to come up with an implementation...
- 'sliding' gradient (as in the video) : very cool, and I know how it could be implemented.

**Comment by MoorPoor** [comment]
Cool! I am curious to try it!
In the end I think it will be pretty important to have a more or less free form solution. symmetrical cropping is an elegant solution, but it restricts you to centered image sections, but that is rather rare the case, right?
You may have noticed that I am very much into collaging with bits and pieces ;)

**Comment by brunoherbelin** [comment]
Crop and masks are now implemented in vimix 0.4.3.  Crop is integrated in Mixing [F2]. The texturing view [F4] offers different masking shapes, with smoothing (maybe one day i'll replace the slider by a grip inside the view, but this is cosmetics). The crop and masks are centered, but the displacement of the texture itself allows selecting which region to show.

In addition, an editable mask will be added to directly 'paint' the mask: i'll try to do this soon...

**Comment by brunoherbelin** [comment]
With the latest implementation of painting of entirely custom mask, the feature is now implemented.

The texture solution (i.e. draw in bitmap) was prefered to the geometrical editing of shapes of the mask that was suggested (the "additional grippers") because it better corresponds to the concept of vimix to perform operations on pixels (i.e. bitmap editor, not vector drawing).
