### ISSUE TITLE
OSC Source Name problem

### ISSUE THREAD

**Issue by lupin3rd** [brunoherbelin/vimix#69]
I'm using beta version on a show. I control alpha value by OSC message... i use current but vimix don't alterate alpha on current video... it use the next video on the list...

**Comment by brunoherbelin** [comment]
Thanks for the bug report!
The only problem is that I cannot replicate it :(
This doesn't mean there is no bug, but that I need more info on the sequence of osc commands that lead to the problem. Thanks for providing more info.

**Comment by lupin3rd** [comment]
Sorry Bruno i do some test and understand that the problem is with source name... not current...
See this video... a little pure data object that send OSC message to vimix... if i use ID works fine, if i use current label works fine... but if i use the source name vimix select another video :-)
https://youtu.be/mJOkgKbU8ss

**Comment by brunoherbelin** [comment]
aha! the problem was a bit more tricky : your source name starts with a number, and vimix was confusing this with the targetting a source by its ID!

I fixed this : please confirm after updating the code from Beta

NB: I thought to enforce that OSC messages to target source by ID should be more explicit, i.e. with a '#' . 
e.g.` /vimix/#2/alpha f 1`
instead of ` /vimix/2/alpha f 1`
But the motivation was that programmatically, it was easier to just give the number, e.g.  loop with n between 0 and N, send the same command with just the target 'n'. Adding the '#' would force a string manipulation. 
But maybe this doesn't matter and it would be more clear to change the API of vimix to add the '#' ?? What's your take on this?

**Comment by brunoherbelin** [comment]
Update: after thinking about it a bit more, I decided that the '#' character should be used (i.e.  `/vimix/#2/alpha`). This is aligned with the way to target batch (e.g. `/vimix/batch#2/alpha`), and with the indication of this ID on the source panel (showing `#2`).

For backward compatibility, the # is not mandatory though. (will just not be in the doc, and might be dropped at some point).

**Comment by lupin3rd** [comment]
I think that # is the right way.
I confirm that now all works fine.
Thank you Bruno.

Il sab 18 mar 2023, 10:34 BHBN ***@***.***> ha scritto:
